name: CI-SZTL
on: 
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Nodejs
        uses: actions/setup-node@v2.5.1
        with:
          node-version: "14.x"
      - name: Install deps
        run: npm install
      - name: build app
        run: npm run build 
      - name: copy dist file with scp
        uses: appleboy/scp-action@v0.0.1
        with: 
          host: "119.91.212.103"
          username: "root"
          password: "123456ok..."
          port: 22
          source: "dist/"
          target: "/var/www/carbon/"
    
